{% set name = "rpy2-arrow" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: eb349f0de6711e85e01921f83a4158396b8411ec31ccaf0e347f5c3ac6f4af1b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - rpy2 >=3.4
    - pyarrow >=5
    - r-arrow >=5

test:
  imports:
    - rpy2_arrow.pyarrow_rarrow
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/rpy2/rpy2-arrow
  summary: Share Apache Arrow datasets between Python and R.
  description: |
    `rpy2-arrow` allows you to share the same arrow datasets between Python and
    R without copying the data. This takes advantage of the Arrow C-API.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matthewwardrop
